Month 8/step 2
R2u1s/react-burger pull request #4
Opened 2023-05-04 10:31 UTC by R2u1s

2023-05-04 11:06 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Раздельное хранение булок и остальных ингредиентов
- Хорошая организация хранилища
- `Dnd` работает хорошо

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Если сделать заказ с дефолтной булкой, то запрос падет с ошибкой, потому что в payload пустой массив.

<img width="1286" alt="Снимок экрана 2023-05-04 в 13 54 37" src="https://user-images.githubusercontent.com/60173362/236184454-3f81b476-ce68-4836-9c9c-1b6abc2e495e.png">

- для атрибута `key` в конструкторе нужно использовать для ингредиента уникальный uuid (Вам нужно его генерировать во время сброса в зону DnD). Это можно делать с помощью библиотеки uuid `https://www.npmjs.com/package/uuid` , или Вам должны были показать, как это сделать, иначе некорректно может работать DND. А в key будет уже просто `key={ item.uuid }`
- Для некоторых компонентов не хватает `propTypes`
- если экшен не выполняет сайдэффектов, то не должна диспатчится функция и пропускатсья через thunk
- уберите захардкоженную булку

Более подробно описание проблемы смотрите комментарии в pull request.

**Можно лучше**
- желательно очищать конструктор после успешного получения номера заказа с сервера в блоке then, чтобы пользователь мог следующий заказ сделать, не удаляя старые ингредиенты
- Не нужно дополнительно хранить в сторе заказаные ингредиенты - это не пригодится в будущем

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-04 11:06 UTC, andryxxa93 commented on src/components/App/App.js
> +  const { ingredientsList, selectedIngredients, currentIngredient, orderInfoNew, ingredientsRequest, ingredientsFailed } = useSelector(store => ({
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-05-04 11:06 UTC, andryxxa93 commented on src/components/ConstructorElementsListItem/ConstructorElementsListItem.js
> +const ConstructorElementsListItem = ({ ingredient, index }) => {
**Надо исправить**

для этого компонента так же нужно описать PropTypes

2023-05-04 11:06 UTC, andryxxa93 commented on src/services/actions/burger.js
> +  return function (dispatch) {
**Надо исправить**

не совсем верно организован диспатчи простых экшенов, не требующих сайд эффектов.

Если действие не требует запросов к серверу или каких то побочных эффектов, то нужно дисптчить просто объект экшена, а не функцию

Например, как сделано сейчас:

Описана функция

```
export const moveConstructorItem = (dragIndex, hoverIndex) => (dispatch) => {
	dispatch({
		type: MOVE_CONSTRUCTOR_ITEM,
		dragIndex,
		hoverIndex,
	});
};

dispatch(moveConstructorItem(dragIndex, hoverIndex)); //будет задиспатчена функция
```

Если присмотреться, то в коде есть два dispatch. Что при этом происходит:

мы диспатчик функцию => thunk перехватывает функцию => thunk выполняет функцию => функция сама диспатчит экшен => экшен попадает в редьюсер

В случае экшена не требующего сайдэффектов 2, 3 и 4 звено в цепочке лишние, т.к. не нужно пропускать простые экшены через thunk

Как должно быть:

```
//такая функция называется action creator - она принимает данные и возвращает объект (а не функцию)
export const moveConstructorItem = (dragIndex, hoverIndex) => ({
	type: MOVE_CONSTRUCTOR_ITEM,
	dragIndex,
	hoverIndex,
});

dispatch(moveConstructorItem(dragIndex, hoverIndex));
```

Но в этом случае будет задиспатчен объект
при этом не будет в цепочке обработки экшена лишних шагов, экшен не будет перехвачен thunk т.к. является объектом, а не функцией, а попадет сразу в редюсер

Нужно исправить это замечание для всех подобных мест в проекте, где при диспатче нужно просто передать экшен в редьюсер, а не выполнять сайдэффекты.

2023-05-04 11:06 UTC, andryxxa93 commented on src/services/reducers/burger.js
> +    bun: {
**Необходимо исправить**
Не надо хардкодить данные - необходимо подставлять данные получаемые с бека.

2023-05-04 11:06 UTC, andryxxa93 commented on src/services/reducers/burger.js
> +    totalPrice: 0
**Можно лучше**

Хотя в задании и предложено вычислять полную стоимость в редьюсере, но это плохая идея, т.к. общая стоимость это производные данные от данных о бургере и сейчас у нас в некотором роде дублируется эта информация (есть массив ингредиентов с ценами и есть отдельно полная стоимость)

Поэтому лучше рассчитывать их не в редьюсере а просто в компоненте конструктора используя useMemo

```
const totalPrice = useMemo(()=> {
   return **рассчет стоимости**
}, burgersData)
```

так стоимость будет перерасчитываться в момент изменения бургера

2023-05-05 08:14 UTC, R2u1s commented on src/services/reducers/burger.js
> +    bun: {
А зачем брать с бэка, если булка ещё не выбрана? Как раз высвечивается, что булка не выбрана

2023-05-06 07:00 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-05-14 14:13 UTC, merged